### ISSUE TITLE
Trocar o Travis CI pelo Github CI 

### ISSUE THREAD

**Issue by carolcodes** [carolcodes/videos-pt.br-tecnologia#121]
Testar temporariamente o CI do Github

**Comment by lucasgomide** [comment]
@carolcodes vc quer tocar isso, se quiser eu posso tocar ;)

**Comment by carolcodes** [comment]
pode tocar e valeu por isso @lucasgomide :black_heart:

**Comment by MuriloEduardo** [comment]
@lucasgomide como está isso? Estou com um tempo livre e começando a contribuir mais ativamente para a comunidade open source. Caso ainda não tenha começado gostaria de resolver essa Issue.

**Comment by lucasgomide** [comment]
Fala @MuriloEduardo, ainda não consegui colocar ernegia nisto. Se você tiver tempo, pode mandar ver nessa parada aê

**Comment by lucasgomide** [comment]
@carolcodes https://github.com/carolcodes/videos-pt.br-tecnologia/pull/154
